//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conferences
    {
        public int idConference { get; set; }
        public string nameConference { get; set; }
        public System.DateTime dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public string place { get; set; }
        public Nullable<int> idForm { get; set; }
        public string description { get; set; }
        public int idStatus { get; set; }
    
        public virtual Forms Forms { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
